export enum ExerciseCategories {
  Abs = 'Abs',
  Back = 'Back',
  Biceps = 'Biceps',
  Calves = 'Calves',
  Chest = 'Chest',
  Compounds = 'Compounds',
  Forearms = 'Forearms',
  'Full Body' = 'Full Body',
  Glutes = 'Glutes',
  Hamstrings = 'Hamstrings',
  Legs = 'Legs',
  Olympic = 'Olympic',
  Shoulders = 'Shoulders',
  Triceps = 'Triceps',
  Quads = 'Quads',
}
